name: "Close Stale Issues"

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 14
          days-before-close: 14
          exempt-issue-labels: 'bug, Put on Hold, In Processing, Investigating'
          close-issue-reason: 'not_planned'
